In [63]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from imblearn.over_sampling import SMOTE
import nltk
import re
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.pipeline import Pipeline

In [ ]:
# data preprocessing

In [74]:
df=pd.read_csv('spam.csv',encoding='ISO-8859-1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [ ]:
here columns Unnamed: 2	Unnamed: 3	Unnamed: 4 not required .so we drop it.

In [75]:
df.drop(columns=['Unnamed: 2'	,'Unnamed: 3'	,'Unnamed: 4'],axis=1,inplace=True)

In [8]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [76]:
df.v1=df.v1.map({'ham':0,'spam':1})

In [77]:
words=nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [78]:
stop=set(stopwords.words('english'))

In [30]:
# preprocessing the text
cleaned_text=[]
def preprocessing(text):
    for word in text:
        lower=word.lower()
        clean=re.sub(r'[^a-z\s]','',lower)
        split=clean.split()
        cleaned=[i for i in split if i not in stop]
        join=''.join(cleaned)
        cleaned_text.append(join)
    return cleaned_text

In [79]:
cleaned_text=[]
for word in df.v2:
    lower=word.lower()
    clean=re.sub(r'[^a-z\s]','',lower)
    split=clean.split()
    cleaned= [i for i in split if i not in stop]
    join=' '.join(cleaned)
    cleaned_text.append(join)

In [40]:
cleaned_text

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry questionstd txt ratetcs apply overs',
 'u dun say early hor u c already say',
 'nah dont think goes usf lives around though',
 'freemsg hey darling weeks word back id like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aids patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitled update latest colour mobiles camera free call mobile update co free',
 'im gonna home soon dont want talk stuff anymore tonight k ive cried enough today',
 'six chances win cash pounds txt csh send cost pday days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim tc wwwdbuknet lccltd pobox ldnwarw',
 'ive searching right words thank breather promise wont take help granted fulfil promise wonderful blessing times',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click httpwap xxxmobilemovieclubcomnqjkgighjjgcbl',
 'oh kim watching',
 'eh u remember spell name yes v naughty make v wet',
 'fine thats way u feel thats way gota b',
 'england v macedonia dont miss goalsteam news txt ur national team eg england trywales scotland txt poboxoxwwq',
 'seriously spell name',
 'im going try months ha ha joking',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'forced eat slice im really hungry tho sucks mark getting worried knows im sick turn pizza lol',
 'lol always convincing',
 'catch bus frying egg make tea eating moms left dinner feel love',
 'im back amp packing car ill let know theres room',
 'ahhh work vaguely remember feel like lol',
 'wait thats still clear sure sarcastic thats x doesnt want live us',
 'yeah got v apologetic n fallen actin like spoilt child got caught till wont go badly cheers',
 'k tell anything',
 'fear fainting housework quick cuppa',
 'thanks subscription ringtone uk mobile charged month please confirm replying yes reply charged',
 'yup ok go home look timings msg xuhui going learn nd may lesson',
 'oops ill let know roommates done',
 'see letter b car',
 'anything lor u decide',
 'hello hows saturday go texting see youd decided anything tomo im trying invite anything',
 'pls go ahead watts wanted sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burns msg tried call reply sms free nokia mobile free camcorder please call delivery tomorrow',
 'seeing',
 'great hope like man well endowed ltgt inches',
 'callsmessagesmissed calls',
 'didnt get hep b immunisation nigeria',
 'fair enough anything going',
 'yeah hopefully tyler cant could maybe ask around bit',
 'u dont know stubborn didnt even want go hospital kept telling mark im weak sucker hospitals weak suckers',
 'thinked first time saw class',
 'gram usually runs like ltgt half eighth smarter though gets almost whole second gram ltgt',
 'k fyi x ride early tomorrow morning hes crashing place tonight',
 'wow never realized embarassed accomodations thought liked since best could always seemed happy cave im sorry didnt dont give im sorry offered im sorry room embarassing',
 'sms ac sptv new jersey devils detroit red wings play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lturlgt',
 'congrats year special cinema pass call c suprman v matrix starwars etc free bxipwe pm dont miss',
 'sorry ill call later meeting',
 'tell reached',
 'yesgauti sehwag odi series',
 'gonna pick burger way home cant even move pain killing',
 'ha ha ha good joke girls situation seekers',
 'part checking iq',
 'sorry roommates took forever ok come',
 'ok lar double check wif da hair dresser already said wun cut v short said cut look nice',
 'valued customer pleased advise following recent review mob awarded bonus prize call',
 'today song dedicated day song u dedicate send ur valuable frnds first rply',
 'urgent ur awarded complimentary trip eurodisinc trav acoentry claim txt dis morefrmmob shracomorsglsuplt ls aj',
 'hear new divorce barbie comes kens stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finished class',
 'hi babe im home wanna something xx',
 'kkwhere youhow performed',
 'u call',
 'waiting machan call free',
 'thats cool gentleman treat dignity respect',
 'like peoples much shy pa',
 'operate ltgt',
 'still looking job much tas earn',
 'sorry ill call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later dont network urgnt sms',
 'real u getting yo need tickets one jacket im done already used multis',
 'yes started send requests make pain came back im back bed double coins factory gotta cash nitros',
 'im really still tonight babe',
 'ela kanoil download come wen ur free',
 'yeah dont stand close tho youll catch something',
 'sorry pain ok meet another night spent late afternoon casualty means havent done stuffmoro includes time sheets sorry',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurts u smile becoz someone still loves see u smiling',
 'please call customer service representative ampm guaranteed cash prize',
 'havent planning buy later check already lido got show e afternoon u finish work already',
 'free ringtone waiting collected simply text password mix verify get usher britney fml',
 'watching telugu moviewat abt u',
 'see finish loads loans pay',
 'hi wk ok hols yes bit run forgot hairdressers appointment four need get home n shower beforehand cause prob u ham',
 'please dont text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x ams xx',
 'im still looking car buy gone driving test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'wow youre right didnt mean guess gave boston men changed search location nyc something changed cuz signin page still says boston',
 'umma life vava umma love lot dear',
 'thanks lot wishes birthday thanks making birthday truly memorable',
 'aight ill hit get cash',
 'would ip address test considering computer isnt minecraft server',
 'know grumpy old people mom like better lying always one play jokes',
 'dont worry guess hes busy',
 'plural noun research',
 'going dinnermsg',
 'im ok wif cos like try new things scared u dun like mah cos u said loud',
 'gent trying contact last weekends draw shows prize guaranteed call claim code k valid hrs ppm',
 'wa ur openin sentence formal anyway im fine juz tt im eatin much n puttin weighthaha anythin special happened',
 'entered cabin pa said happy bday boss felt special askd lunch lunch invited apartment went',
 'winner u specially selected receive holiday flights inc speak live operator claim pmin',
 'goodo yes must speak friday eggpotato ratio tortilla needed',
 'hmmmy uncle informed hes paying school directly pls buy food',
 'private account statement shows unredeemed bonus points claim call identifier code expires',
 'urgent mobile awarded bonus caller prize final try contact u call landline boxwrc ppm',
 'new address applespairsall malarky',
 'todays voda numbers ending selected receive award match please call quoting claim code standard rates app',
 'going sao mu today done',
 'predict wat time finish buying',
 'good stuff',
 'knowyetunde hasnt sent money yet sent text bother sending dont involve anything shouldnt imposed anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'kkhow much cost',
 'im home',
 'dear call tmorrowpls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sptyrone',
 'want get laid tonight want real dogging locations sent direct ur mob join uks largest dogging network bt txting gravel nt eca pmsgp',
 'haf msn yijuehotmailcom',
 'call meet',
 'check rooms befor activities',
 'youll rcv msgs chat svc free hardcore services text go u get nothing u must age verify yr network try',
 'got c lazy type forgot lect saw pouch like v nice',
 'k text youre way',
 'sir waiting mail',
 'swt thought nver get tired little things lovable persons cozsomtimes little things occupy biggest part hearts gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name taking class us',
 'freemsg havent replied text im randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummmawill call check inour life begin qatar pls pray hard',
 'ki deleted contact',
 'sindu got job birla soft',
 'wine flowing im nevering',
 'yup thk cine better cos need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'everywhere dirt floor windows even shirt sometimes open mouth comes flowing dream world without half chores time joy lots tv shows ill see guess like things must exist like rain hail mist time done become one',
 'aaooooright work',
 'im leaving house',
 'hello love get interview today happy good boy think meare missing',
 'customer service annoncement new years delivery waiting please call arrange delivery',
 'winner u specially selected receive cash holiday flights inc speak live operator claim',
 'keep safe need miss already envy everyone sees real life',
 'new car house parentsi new job hand',
 'im love im excited day spend make happy',
 'pls stop bootydelious f inviting friend reply yes see wwwsmsacubootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internetservice menu',
 'place ur points e cultures module already',
 'urgent trying contact last weekends draw shows prize guaranteed call claim code valid hrs',
 'hi frnd best way avoid missunderstding wit beloved ones',
 'great escape fancy bridge needs lager see tomo',
 'yes completely formclark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time coming later',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begins',
 'well im gonna finish bath goodfine night',
 'let know youve got money carlos make call',
 'u still going mall',
 'turns friends staying whole show wont back til ltgt feel free go ahead smoke ltgt worth',
 'text doesnt reply let know log',
 'hi spoke maneesha v wed like know satisfied experience reply toll free yes',
 'lifted hopes offer money need especially end month approaches hurts studying anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guys close',
 'going nothing greatbye',
 'hello handsome finding job lazy working towards getting back net mummy wheres boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone ampm guaranteed cash prize',
 'got xmas radio times get',
 'jus reached home go bathe first sis using net tell u finishes k',
 'unique enough find th august wwwareyouuniquecouk',
 'im sorry ive joined league people dont keep touch mean great deal friend times even great personal cost great week',
 'hi finally completed course',
 'stop however suggest stays someone able give ors every stool',
 'hope youve settled new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got persons story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate evening hope see tomorrow bit bloody babyjontet txt back u xxx',
 'found enc ltgt',
 'sent ltgt bucks',
 'hello darlin ive finished college txt u finish u love kate xxx',
 'account refilled successfully inr ltdecimalgt keralacircle prepaid account balance rs ltdecimalgt transaction id kr ltgt',
 'goodmorning sleeping ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'entered cabin pa said happy bday boss felt special askd lunch lunch invited apartment went',
 'aight yo dats straight dogg',
 'please give us connection today ltdecimalgt refund bill',
 'shoot big loads get ready',
 'whats bruv hope great break rewarding semester',
 'home always chat',
 'kkgoodstudy well',
 'yup noe leh',
 'sounds great home',
 'finally match heading towards draw prediction',
 'tired havent slept well past nights',
 'easy ahsen got selected means good',
 'take exam march',
 'yeah think use gt atm register sure theres anyway help let know sure ready',
 'ok prob take ur time',
 'os called ubandu run without installing hard diskyou use os copy important files system give repair shop',
 'sorry ill call later',
 'u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh',
 'new mobiles must go txt nokia collect todayfrom wwwtcbiz optout gbpmtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo followed ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teaches lesson amp conducts exam life first conducts exam amp teaches lessons happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side ltgt street road turn first right',
 'dear going rubber place',
 'sorry battery died yeah im',
 'yeshere tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recdthirtyeight pence',
 'printed oh ltgt come upstairs',
 'ill little closer like bus stop street',
 'youwhen wil reach',
 'new theory argument wins situation loses person dont argue ur friends kick amp say im always correct',
 'u secret admirer looking make contact ufind rreveal thinks ur specialcall',
 'tomarrow final hearing laptop case cant',
 'pleassssssseeeeee tel v avent done sportsx',
 'okay shining meant signing sounds better',
 'although told u dat im baig face watches really like e watch u gave cos fr u thanx everything dat uve done today im touched',
 'u dont remember old commercial',
 'late said website didnt dont slippers',
 'asked call ok',
 'kallis wont bat nd innings',
 'didnt work oh ok goodnight ill fix ready time wake dearly missed good night sleep',
 'congratulations ur awarded cd vouchers gift guaranteed free entry wkly draw txt music tncs wwwldewcomwinppmxage',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 'doinghow',
 'ups days also shipping company takes wks way usps takes week gets lag may bribe nipost get stuff',
 'im back lemme know youre ready',
 'dont necessarily expect done get back though im headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'tried contact reply offer video handset anytime networks mins unlimited text camcorder reply call',
 'im parked next mini coming today think',
 'yup',
 'anyway im going shopping cos sis done yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charged pm unsubscribe text stop',
 'dint come us',
 'wana plan trip sometme',
 'sure yet still trying get hold',
 'ur ringtone service changed free credits go clubmobilescom choose content stop txt club stop pwk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk singles chart mobile week choose top quality ringtone message free charge',
 'come mu sorting narcotics situation',
 'night ended another day morning come special way may smile like sunny rays leaves worries blue blue bay',
 'hmv bonus special pounds genuine hmv vouchers answer easy questions play send hmv infowwwpercentrealcom',
 'usf guess might well take car',
 'objection bf coming',
 'thanx',
 'tell rob mack gf theater',
 'awesome ill see bit',
 'sent type food like',
 'done handed celebrations full swing yet',
 'got called tool',
 'wen u miss someone',
 'ok asked money far',
 'okie',
 'yeah think usual guys still passed last night get ahold anybody let know ill throw',
 'k might come tonight class lets early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life means lot love life love people life world calls friends call world ge',
 'dearshall mail tonitebusy streetshall update tonitethings looking okvarunnathu edukkukayee raksha ollubut good one real sense',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam working',
 'oops got bit',
 'much buzy',
 'accidentally deleted message resend please',
 'tmobile customer may claim free camera phone upgrade pay go sim card loyalty call offer ends thfebtcs apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomocant believe time week already',
 'awesome remember last time got somebody high first time diesel v',
 'shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sms ac blind date u rodds aberdeen united kingdom check httpimg sms acwicmbcktzr blind dates send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hanging thread cause u wont buy stuff',
 'themob check newest selection content games tones gossip babes sport keep mobile fit funky text wap',
 'garage keys arent bookshelf',
 'today accept dayu accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply means enemy',
 'think ur smart win week weekly quiz text play nowtcs winnersclub po box uz gbpweek',
 'says hell give call friends got money hes definitely buying end week',
 'hi way u day normal waythis real ur uniquei hope know u rest mylife hope u find wot lost',
 'made day great day',
 'kkadvance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'really dude friends im afraid',
 'december mobile mths entitled update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kisses',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l cos buses hav gon past cos full im still waitin pete x',
 'would great well guild could meet bristol road somewhere get touch weekend plans take flight good week',
 'problem',
 'callsmessagesmissed calls',
 'hi dahow todays class',
 'id say thats good sign well know track record reading women',
 'cool text youre parked',
 'im reading text sent meant joke read light',
 'kkapo kgood movie',
 'maybe could get book tomo return immediately something',
 'call germany pence per minute call fixed line via access number prepayment direct access',
 'chance might evaporated soon violated privacy stealing phone number employers paperwork cool please contact report supervisor',
 'valentines day special win quiz take partner trip lifetime send go pmsg rcvd custcare',
 'tadaaaaa home babe still',
 'cool come havent wined dined',
 'sleepingand surfing',
 'sorry ill call later',
 'u calling right call hand phone',
 'ok thats great thanx lot',
 'take post come must texts happy reading one wiv hello caroline end favourite bless',
 'u hiding stranger',
 'interested like',
 'sister cleared two round birla soft yesterday',
 'gudnitetcpractice going',
 'dis yijue jus saw ur mail case huiming havent sent u num dis num',
 'one small prestige problem',
 'fancy shag dointerested sextextukcom txt xxuk suzy txts cost per msg tncs website x',
 'checking really miss seeing jeremiah great month',
 'nah cant help ive never iphone',
 'youre car hour half im going apeshit',

In [80]:
df['cleaned_text']=cleaned_text

In [81]:
df.rename(columns={'v1':'labels'},inplace=True)

In [82]:
df

,labels,v2,cleaned_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,0,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,0,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah dont think goes usf lives around though
...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,nd time tried contact u u pound prize claim ea...
5568,0,Will Ì_ b going to esplanade fr home?,b going esplanade fr home
5569,0,"Pity, * was in mood for that. So...any other s...",pity mood soany suggestions
5570,0,The guy did some bitching but I acted like i'd...,guy bitching acted like id interested buying s...
5571,0,Rofl. Its true to its name,rofl true name

In [83]:
df.drop('v2',axis=1,inplace=True)

In [84]:
df

      labels                                       cleaned_text
0          0  go jurong point crazy available bugis n great ...
1          0                            ok lar joking wif u oni
2          1  free entry wkly comp win fa cup final tkts st ...
3          0                u dun say early hor u c already say
4          0        nah dont think goes usf lives around though
...      ...                                                ...
5567       1  nd time tried contact u u pound prize claim ea...
5568       0                          b going esplanade fr home
5569       0                        pity mood soany suggestions
5570       0  guy bitching acted like id interested buying s...
5571       0                                     rofl true name

[5572 rows x 2 columns]

In [85]:
# convert text into numerical by using countvectorizer or tfidfvectorizer

tfidf=TfidfVectorizer()
x=tfidf.fit_transform(df['cleaned_text'])
y=df['labels']

In [121]:
# splitting data for training ,testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=32)

In [87]:
# building the model
multinb=MultinomialNB()

In [88]:
# train the model
multinb.fit(x_train,y_train)

MultinomialNB()

In [89]:
pred=multinb.predict(x_test)

In [90]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       1.00      0.76      0.86       149

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.97      1115

In [91]:
confusion_matrix(y_test,pred)

array([[966,   0],
       [ 36, 113]], dtype=int64)

In [92]:
# build the pipeline
pipe=Pipeline([('tfidfvectorizer',TfidfVectorizer()),('model',MultinomialNB())])

In [93]:
# x=df['cleaned_text']
# y=df['labels']

In [122]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('model', MultinomialNB())])

In [98]:
pipe.predict(['congratulation you won 1 lakh prize '])

array([1], dtype=int64)

In [100]:
# top 10 spam words
feature_names=tfidf.get_feature_names_out()

In [103]:
clasess=multinb.classes_

In [108]:
spam_index=list(clasess).index(1)

In [115]:
spam_proba=multinb.feature_log_prob_[spam_index]

In [118]:
top=10
top_10_spam_index=np.argsort(spam_proba)[-top:]

In [119]:
feature_names[top_10_spam_index]

array(['reply', 'stop', 'text', 'prize', 'ur', 'mobile', 'claim', 'txt',
       'free', 'call'], dtype=object)

In [124]:
pred=pipe.predict(x_test)

In [125]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       966
           1       0.99      0.79      0.88       149

    accuracy                           0.97      1115
   macro avg       0.98      0.89      0.93      1115
weighted avg       0.97      0.97      0.97      1115

In [126]:
confusion_matrix(y_test,pred)

array([[965,   1],
       [ 32, 117]], dtype=int64)